project:
  type: website
  output-dir: docs

website:
  title: "Neerja Kasture's Blog"
  site-url: https://neerjakasture.github.io/blog
  navbar:
    right:
      - text: Homepage
        href: https://neerjakasture.github.io
      # - text: "About"
      #   href: about.qmd
  page-footer:
    center: "© 2025 Neerja Kasture"

format:
  html:
    theme: 
      light: 
        - united
        - custom.scss
      dark: 
        - superhero
        - custom.scss
    toggle: true
    respect-user-color-scheme: true


